#!/bin/mksh
#-
# Copyright (c) 2021 Dominik George, credativ GmbH <dominik.george@credativ.de>
# Copyright (c) 2021 Mathis Rudolf, credativ GmbH <mathis.rudolf@credativ.de>
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose, without fee, and without a written agreement
# is hereby granted, provided that the above copyright notice and this
# paragraph and the following two paragraphs appear in all copies.
#
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
# DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
# LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS
# DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
# ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO
# PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

config_prefix=plsh_mtb

bailout() {
    print -ru2 "$*"
    exit 1
}

is_valid_name() {
    # Vreify that argument is a valid name and safe for inserting into psql

    name=$1
    if [[ "$name" = +([A-Za-z0-9_]) ]]; then
	return 0
    else
	bailout "$name is not a valid name"
    fi
}

get_config() {
    # Get a system setting from the plsh_mtb prefix

    param=$1; is_valid_name "$param"

    output=$(psql -AtX -c "SHOW $config_prefix.$param" 2>&1) || bailout "$output"
    echo "${output}"
}

# Start Backup
backup_start() {

}

# Stop Backup
backup_stop() {

}

# Remove Backup
backup_rm() {

}

# Restore Backup
backup_restore() {

}

# Lists Backups and Stats
backup_infos() {

}

# Lists Stats of Current Backup
backup_info() {

}
